// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using University.DataLayer;

namespace University.DataLayer.Migrations
{
    [DbContext(typeof(VuDbContext))]
    [Migration("20210317193258_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("GroupStudent", b =>
                {
                    b.Property<long>("GroupsId")
                        .HasColumnType("bigint")
                        .HasColumnName("groups_id");

                    b.Property<long>("StudentsId")
                        .HasColumnType("bigint")
                        .HasColumnName("students_id");

                    b.HasKey("GroupsId", "StudentsId")
                        .HasName("pk_group_student");

                    b.HasIndex("StudentsId")
                        .HasDatabaseName("ix_group_student_students_id");

                    b.ToTable("group_student");
                });

            modelBuilder.Entity("Velvetech.DomainLayer.Entities.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.ToTable("groups");
                });

            modelBuilder.Entity("Velvetech.DomainLayer.Entities.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("first_name");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("last_name");

                    b.Property<string>("Nickname")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("nickname");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("patronymic");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.ToTable("students");
                });

            modelBuilder.Entity("GroupStudent", b =>
                {
                    b.HasOne("Velvetech.DomainLayer.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .HasConstraintName("fk_group_student_groups_groups_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Velvetech.DomainLayer.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .HasConstraintName("fk_group_student_students_students_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
